[package]
name = "counter-project"
description = "A TON blockchain project"
version = "0.1.0"
license = "MIT"

[contracts.counter]
name = "counter"
src = "contracts/src/counter.tolk"
depends = []

[test]

[fmt]
width = 100
ignore = []

[scripts]
deploy-emulation = "acton script contracts/scripts/deploy.tolk"
deploy-testnet = "acton script contracts/scripts/deploy.tolk --broadcast --net testnet"

[mappings]
acton = ".acton"
contracts = "contracts/src"
tests = "contracts/tests"
wrappers = "contracts/tests/wrappers"
gen = "gen"
