[package]
name = "acton-contracts"
description = "Rewritten Acton contracts monorepo"
version = "0.1.0"
license = "MIT"

# Counter
[contracts.counter]
name = "counter"
src = "counter/contracts/counter.tolk"
depends = []

# Notcoin 
[contracts.notcoin_minter]
name = "notcoin_minter"
src = "notcoin/contracts/jetton-minter-contract.tolk"
depends = []

[contracts.notcoin_wallet]
name = "notcoin_wallet"
src = "notcoin/contracts/jetton-wallet-contract.tolk"
depends = []

# Acton Jetton
[contracts.acton_jetton_minter]
name = "acton_jetton_minter"
src = "acton-jetton/contracts/jetton-minter-contract.tolk"
depends = ["acton_jetton_wallet"]

[contracts.acton_jetton_wallet]
name = "acton_jetton_wallet"
src = "acton-jetton/contracts/jetton-wallet-contract.tolk"
depends = []

[test]

[fmt]
width = 100
ignore = []

[scripts]
test-counter = "acton test counter/tests"
test-notcoin = "acton test notcoin/tests"
test-acton-jetton = "acton test acton-jetton/tests"

[mappings]
acton = ".acton"
contracts = "contracts"
gen = "gen"
tests = "tests"
wrappers = "tests/wrappers"
