[package]
name = "acton-contracts"
description = "Rewritten Acton contracts monorepo"
version = "0.1.0"
license = "MIT"

# Counter
[contracts.counter]
name = "counter"
src = "counter/contracts/counter.tolk"
depends = []

# Notcoin 
[contracts.notcoin_minter]
name = "notcoin_minter"
src = "notcoin/contracts/jetton-minter-contract.tolk"
depends = []

[contracts.notcoin_wallet]
name = "notcoin_wallet"
src = "notcoin/contracts/jetton-wallet-contract.tolk"
depends = []

# Acton Jetton
[contracts.acton_jetton_minter]
name = "acton_jetton_minter"
src = "acton-jetton/contracts/jetton-minter-contract.tolk"
depends = [{ name = "acton_jetton_wallet", function = "actonJettonWalletCompiledCode" }]

[contracts.acton_jetton_wallet]
name = "acton_jetton_wallet"
src = "acton-jetton/contracts/jetton-wallet-contract.tolk"
depends = []

# DNS
[contracts.dns_collection]
name = "dns_collection"
src = "dns/contracts/nft-collection-contract.tolk"
depends = []

[contracts.dns_item]
name = "dns_item"
src = "dns/contracts/nft-item-contract.tolk"
depends = []

[contracts.dns_root]
name = "dns_root"
src = "dns/contracts/root-dns-contract.tolk"
depends = []

# NFT
[contracts.nft-collection]
name = "Collection"
src = "nft/contracts/nft-collection-contract.tolk"
depends = ["nft-item"]

[contracts.nft-item]
name = "Item"
src = "nft/contracts/nft-item-contract.tolk"
depends = []

# W5
[contracts.w5]
name = "Wallet W5"
src = "w5/contracts/wallet-v5-contract.tolk"
depends = []

[lint.acton_jetton_minter]
asm-function-missing-safety-comment = "allow"

[test]

[build]
output-fift = "build/fift"

[lint.rules]
unused-import = "allow"

[fmt]
width = 100
ignore = []

[scripts]
test-counter = "acton test counter/tests"
test-nft = "acton test nft/tests"
test-notcoin = "acton test notcoin/tests"
test-acton-jetton = "acton test acton-jetton/tests"
test-dns = "acton test dns/tests"
test-w5 = "acton test w5/tests"

[mappings]
acton = ".acton"
contracts = "contracts"
gen = "gen"
tests = "tests"
wrappers = "tests/wrappers"
