[package]
name = "acton-contracts"
description = "Rewritten Acton contracts monorepo"
version = "0.1.0"
license = "MIT"

# Counter
[contracts.Counter]
display-name = "Counter"
src = "counter/contracts/Counter.tolk"
depends = []

# Config
[contracts.Config]
display-name = "Config"
src = "config/contracts/Config.tolk"
depends = []

# Notcoin 
[contracts.NotcoinMinter]
display-name = "NotcoinMinter"
src = "notcoin/contracts/NotcoinMinter.tolk"
depends = []

[contracts.NotcoinWallet]
display-name = "NotcoinWallet"
src = "notcoin/contracts/NotcoinWallet.tolk"
depends = []

# Jetton v2
[contracts.JettonMinter]
display-name = "JettonMinter"
src = "jetton-v2/contracts/JettonMinter.tolk"
depends = [{ name = "JettonWallet", function = "jettonWalletCompiledCode" }]

[contracts.JettonWallet]
display-name = "JettonWallet"
src = "jetton-v2/contracts/JettonWallet.tolk"
depends = []

# DNS
[contracts.DnsCollection]
display-name = "DnsCollection"
src = "dns/contracts/DnsCollection.tolk"
depends = []

[contracts.DnsItem]
display-name = "DnsItem"
src = "dns/contracts/DnsItem.tolk"
depends = []

[contracts.RootDns]
display-name = "RootDns"
src = "dns/contracts/RootDns.tolk"
depends = []

# Highload v3
[contracts.HighloadWalletV3]
display-name = "HighloadWalletV3"
src = "highload-v3/contracts/HighloadWalletV3.tolk"
depends = []

# Multisig v2
[contracts.Multisig]
display-name = "Multisig"
src = "multisig-v2/contracts/Multisig.tolk"
depends = [{ name = "Order", function = "orderCompiledCode" }]

[contracts.Order]
display-name = "Order"
src = "multisig-v2/contracts/Order.tolk"
depends = []

# NFT
[contracts.NftCollection]
display-name = "NftCollection"
src = "nft/contracts/NftCollection.tolk"
depends = ["NftItem"]

[contracts.NftItem]
display-name = "NftItem"
src = "nft/contracts/NftItem.tolk"
depends = []

# Elector
[contracts.Elector]
display-name = "Elector"
src = "elector/contracts/Elector.tolk"

# W5
[contracts.WalletV5]
display-name = "WalletV5"
src = "w5/contracts/WalletV5.tolk"
depends = []

[lint.JettonMinter]
asm-function-missing-safety-comment = "allow"

[test]

[build]
output-fift = "build/fift"

[lint]
max-warnings = 0

[lint.rules]
explicit-return-type = "allow"
unused-import = "allow"

[fmt]
width = 100
ignore = []

[scripts]
test-counter = "acton test counter/tests"
test-nft = "acton test nft/tests"
test-notcoin = "acton test notcoin/tests"
"test-jetton-v2" = "acton test jetton-v2/tests"
test-dns = "acton test dns/tests"
test-w5 = "acton test w5/tests"
test-highload = "acton test highload-v3/tests"
test-elector = "acton test elector/tests"

[mappings]
acton = ".acton"
contracts = "contracts"
gen = "gen"
tests = "tests"
wrappers = "tests/wrappers"
