import "@acton/io"
import "@acton/emulation/network"
import "@acton/emulation/scripts"
import "utils/common"
import "../wrappers/JettonMinter.gen"

fun main() {
    val admin = promptJettonWallet("JETTON_ADMIN", "Select Current Admin ActonWallet");
    val minter = promptJettonMinter("Enter Jetton Minter address");
    val nextAdmin = promptJettonAddress(
        "JETTON_NEXT_ADMIN",
        "Enter next admin address",
        admin.address,
    );

    val res = minter.sendChangeMinterAdmin(
        admin.address,
        0,
        nextAdmin,
        { bounce: false, value: grams("0.05") },
    );
    println(res.waitForTrace());

    println("JETTON NEXT_ADMIN_REQUESTED={}", nextAdmin);
    printJettonMinterInfo(minter, "JETTON");
}
