name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Setup Acton
        uses: i582/setup-acton@master

      - name: Install Node dependencies
        run: npm ci

      - name: Build
        run: acton build

      - name: Test
        run: npm test

      - name: Build App
        run: npm run app:build

      - name: Linter
        run: acton check --output-format github

      - name: Formatter
        run: acton fmt --check
