name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22
          cache: npm

      - name: Setup Acton
        uses: ton-blockchain/setup-acton@82b1fb8d8f60584dd552f4014b3cd2de2e599dfb

      - name: Install Node dependencies
        run: npm ci

      - name: Test
        run: npm run test

      - name: Typecheck
        run: npm run typecheck

      - name: Build
        run: npm run build

      - name: Linter
        run: acton check --output-format github

      - name: Acton Formatter
        run: acton fmt --check

      - name: Prettier
        run: npm run fmt:check
