name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: false # ton/setup-acton is not yet available
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Acton
        uses: ton/setup-acton@v2

      - name: Build
        run: acton build

      - name: Test
        run: acton test
