name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubicloud-standard-4
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Acton
        uses: i582/setup-acton@v0.0.1
        with:
          github-token: ${{ secrets.ACTON_TOKEN }}

      - name: Version
        run: acton --version

      - name: Build
        run: acton build

      - name: Test
        run: acton test

      - name: Linter
        run: acton check

      - name: Formatter
        if: false
        run: acton fmt --check
